#!/usr/bin/env python3
"""Generate language registries from the browser demo contract schema."""

import argparse
import json
from pathlib import Path
from pprint import pformat


ROOT = Path(__file__).resolve().parents[1]
OUTPUTS = {
    Path("tests/demo_contract_generated.py"): "python",
    Path("docs/demo-contract.js"): "javascript",
}


def _registries(schema):
    required_fields = dict(schema["required_fields"])
    required_fields["node_kinds"] = schema["node_fields"]
    return {
        "SCHEMA_VERSION": schema["schema_version"],
        "NODE_KINDS": tuple(schema["node_kinds"]),
        "ACTION_KINDS": tuple(schema["action_kinds"]),
        "REQUIRED_FIELDS": required_fields,
    }


def _render_python(registries):
    lines = [
        '"""Generated by tools/generate_demo_contract.py. Do not edit."""',
        "",
    ]
    for name in ("SCHEMA_VERSION", "NODE_KINDS", "ACTION_KINDS", "REQUIRED_FIELDS"):
        lines.append(f"{name} = {pformat(registries[name], sort_dicts=True, width=88)}")
        lines.append("")
    return "\n".join(lines)


def _render_javascript(registries):
    lines = ["// Generated by tools/generate_demo_contract.py. Do not edit.", ""]
    for name in ("SCHEMA_VERSION", "NODE_KINDS", "ACTION_KINDS", "REQUIRED_FIELDS"):
        value = registries[name]
        if isinstance(value, tuple):
            value = list(value)
        rendered = json.dumps(value, indent=2, sort_keys=True, ensure_ascii=False)
        lines.append(f"export const {name} = Object.freeze({rendered});")
        lines.append("")
    return "\n".join(lines)


def generate(schema_path="demo/schema-v1.json", check=False):
    """Write or verify tests/demo_contract_generated.py and docs/demo-contract.js."""
    source = Path(schema_path)
    if not source.is_absolute():
        source = ROOT / source
    schema = json.loads(source.read_text(encoding="utf-8"))
    registries = _registries(schema)
    rendered = {
        "python": _render_python(registries),
        "javascript": _render_javascript(registries),
    }
    stale = []
    for relative_path, output_kind in OUTPUTS.items():
        path = ROOT / relative_path
        content = rendered[output_kind]
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            stale.append(relative_path.as_posix())
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8")
    if check:
        for relative_path in stale:
            print(relative_path)
    return stale


def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    stale = generate(check=args.check)
    return 1 if args.check and stale else 0


if __name__ == "__main__":
    raise SystemExit(main())
